# Generated by Django 3.1.1 on 2020-09-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norawebapp', '0003_auto_20200921_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemenu',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='employeemenu',
            name='option_selected',
            field=models.CharField(choices=[('1', 'Opción 1'), ('2', 'Opción 2'), ('3', 'Opción 3'), ('4', 'Opción 4')], default='1', max_length=100, verbose_name='Opción de menú'),
        ),
    ]
